config/routes.rb
Rails.application.routes.draw do

  require 'sidekiq/web'
  mount Sidekiq::Web => '/admin/sidekiq'

  resources :photos
  resources :cars
  resources :brands
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/photo.rb
# == Schema Information
#
# Table name: photos
#
#  id         :integer          not null, primary key
#  car_id     :integer
#  name       :string(255)
#  image      :string(255)
#  photo      :string(255)
#  color      :string(255)
#  background :string(255)
#  price      :string(255)
#  remark     :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Photo < ApplicationRecord
  belongs_to :car

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]

  # GET /photos
  # GET /photos.json
  def index
    # @photos = Photo.all

    @q = Photo.search(params[:q])
    @photos = @q.result().paginate(:page => params[:page], :per_page => 30)
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
  end

  # GET /photos/new
  def new
    @photo = Photo.new
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(photo_params)

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: 'Photo was successfully created.' }
        format.json { render :show, status: :created, location: @photo }
      else
        format.html { render :new }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to photos_url, notice: 'Photo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:car_id, :name, :image, :photo, :color, :background, :price, :remark)
    end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_form.html.erb
<%= form_with(model: photo, local: true) do |form| %>
  <% if photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% photo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :car_id %>
    <%= form.number_field :car_id, id: :photo_car_id %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :photo_name %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image, id: :photo_image %>
  </div>

  <div class="field">
    <%= form.label :photo %>
    <%= form.text_field :photo, id: :photo_photo %>
  </div>

  <div class="field">
    <%= form.label :color %>
    <%= form.text_field :color, id: :photo_color %>
  </div>

  <div class="field">
    <%= form.label :background %>
    <%= form.text_field :background, id: :photo_background %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :photo_price %>
  </div>

  <div class="field">
    <%= form.label :remark %>
    <%= form.text_field :remark, id: :photo_remark %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/photos/edit.html.erb
<h1>Editing Photo</h1>

<%= render 'form', photo: @photo %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Photos</h1>

<table>
  <thead>
    <tr>
      <th>Car</th>
      <th>Name</th>
      <th>Image</th>
      <th>Photo</th>
      <th>Color</th>
      <th>Background</th>
      <th>Price</th>
      <th>Remark</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @photos.each do |photo| %>
      <tr>
        <td><%= photo.car_id %></td>
        <td><%= photo.name %></td>
        <td><%= photo.image %></td>
        <td><%= photo.photo %></td>
        <td><%= photo.color %></td>
        <td><%= photo.background %></td>
        <td><%= photo.price %></td>
        <td><%= photo.remark %></td>
        <td><%= link_to 'Show', photo %></td>
        <td><%= link_to 'Edit', edit_photo_path(photo) %></td>
        <td><%= link_to 'Destroy', photo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @photos %>

<br>

<%= link_to 'New Photo', new_photo_path %>

app/views/photos/new.html.erb
<h1>New Photo</h1>

<%= render 'form', photo: @photo %>

<%= link_to 'Back', photos_path %>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Car:</strong>
  <%= @photo.car_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @photo.name %>
</p>

<p>
  <strong>Image:</strong>
  <%= @photo.image %>
</p>

<p>
  <strong>Photo:</strong>
  <%= @photo.photo %>
</p>

<p>
  <strong>Color:</strong>
  <%= @photo.color %>
</p>

<p>
  <strong>Background:</strong>
  <%= @photo.background %>
</p>

<p>
  <strong>Price:</strong>
  <%= @photo.price %>
</p>

<p>
  <strong>Remark:</strong>
  <%= @photo.remark %>
</p>

<%= link_to 'Edit', edit_photo_path(@photo) %> |
<%= link_to 'Back', photos_path %>