config/routes.rb
Rails.application.routes.draw do

  require 'sidekiq/web'
  mount Sidekiq::Web => '/admin/sidekiq'

  resources :photos
  resources :cars
  resources :brands
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/car.rb
# == Schema Information
#
# Table name: cars
#
#  id         :integer          not null, primary key
#  brand_id   :integer
#  sub_barnd  :string(255)
#  price      :string(255)
#  remark     :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  name       :string(255)
#

class Car < ApplicationRecord
  validates :name, uniqueness: { scope: :brand_id }

  has_many :photos
  belongs_to :brand

  def series_id
    self.remark.split('/')[3]
  end

  def url_list(id)
    [
      {url: "https://car.autohome.com.cn/pic/series-t/#{id}-1-p1.html",name: "t-#{id}-1-p1.html"},
      {url: "https://car.autohome.com.cn/pic/series/#{id}-1-p1.html",name: "#{id}-1-p1.html"},
    ]
  end

  # Car.new.down_file(url, filename)
  def down_file(url, filename)
    url = URI.parse("#{url}")
    res = Net::HTTP.get_response(url)
    File.open("#{filename}", "w:UTF-8") {|f|
        f.write res.body.force_encoding("UTF-8")
    }
  end

  def download_html_page
    Car.all.each do |car|
      down_path = "#{Rails.root}/tmp/html/#{car.id}"
      FileUtils.mkdir_p(down_path)
      p car.series_id
      url_list(car.series_id).each do |arr|
        # p arr[:url]
        # p "#{down_path}/#{arr[:name]}"åå
        # down_file(arr[:url], "#{down_path}/#{arr[:name]}")
        DownloadHtmlWorker.perform_async(arr[:url], "#{down_path}/#{arr[:name]}")
      end
    end
  end

  # def html_abs_path(car)
  #   [
  #     "#{Rails.root}/tmp/html/#{car.id}/#{car.series_id}-1-p1.html.html",
  #     "#{Rails.root}/tmp/html/#{car.id}/t-#{car.series_id}-1-p1.html",
  #   ]
  # end
  # # test_first
  # def test_first
  #   car = Car.first
  #   f = html_abs_path(car)[0]
  #   p f
  #   page = File.open(HTML_FILE) { |f| Nokogiri::HTML(f) }
  #   page
  # end

  def test_a
    f = "/Users/chenwei/workspace/project/autohome/tmp/html/12/t-3170-1-p1.html"
    page = File.open(HTML_FILE) { |f| Nokogiri::HTML(f) }
    page
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy]

  # GET /cars
  # GET /cars.json
  def index
    # @cars = Car.all

    @q = Car.search(params[:q])
    @cars = @q.result().paginate(:page => params[:page], :per_page => 30)
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url, notice: 'Car was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:brand_id, :sub_barnd, :price, :remark)
    end
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_form.html.erb
<%= form_with(model: car, local: true) do |form| %>
  <% if car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
      <% car.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :brand_id %>
    <%= form.number_field :brand_id, id: :car_brand_id %>
  </div>

  <div class="field">
    <%= form.label :sub_barnd %>
    <%= form.text_field :sub_barnd, id: :car_sub_barnd %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :car_price %>
  </div>

  <div class="field">
    <%= form.label :remark %>
    <%= form.text_field :remark, id: :car_remark %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<h1>Editing Car</h1>

<%= render 'form', car: @car %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %>

app/views/cars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cars</h1>

<table>
  <thead>
    <tr>
      <th>Brand</th>
      <th>Sub barnd</th>
      <th>Price</th>
      <th>Remark</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cars.each do |car| %>
      <tr>
        <td><%= car.brand_id %></td>
        <td><%= car.sub_barnd %></td>
        <td><%= car.price %></td>
        <td><%= car.remark %></td>
        <td><%= link_to 'Show', car %></td>
        <td><%= link_to 'Edit', edit_car_path(car) %></td>
        <td><%= link_to 'Destroy', car, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @cars %>
<br>

<%= link_to 'New Car', new_car_path %>

app/views/cars/new.html.erb
<h1>New Car</h1>

<%= render 'form', car: @car %>

<%= link_to 'Back', cars_path %>

app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Brand:</strong>
  <%= @car.brand_id %>
</p>

<p>
  <strong>Sub barnd:</strong>
  <%= @car.sub_barnd %>
</p>

<p>
  <strong>Price:</strong>
  <%= @car.price %>
</p>

<p>
  <strong>Remark:</strong>
  <%= @car.remark %>
</p>

<%= link_to 'Edit', edit_car_path(@car) %> |
<%= link_to 'Back', cars_path %>